source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'smallsteps' do
    pod 'Alamofire', '~> 4.7'
    pod 'Alamofire-Synchronous', '~> 4.0'
    pod 'SwiftyJSON'
end
