source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'smallsteps' do
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON'
    pod 'Eureka'
    pod "StompClientLib"
    pod 'PopupWindow'
    pod 'Starscream'
end
